/*
* generated by Xtext
*/
package org.xtext.grl.tgrl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TGRLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.grl.tgrl.ui.internal.TGRLActivator.getInstance().getInjector("org.xtext.grl.tgrl.TGRL");
	}
	
}
