/*
 * generated by Xtext
 */
package org.xtext.grl.tgrl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractTGRLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.xtext.grl.tgrl.tGRL.TGRLPackage.eINSTANCE);
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http:///grl.ecore"));
		return result;
	}
}
