/*
* generated by Xtext
*/
package org.xtext.grl.tgrl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TGRLStandaloneSetup extends TGRLStandaloneSetupGenerated{

	public static void doSetup() {
		new TGRLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

