/*
 * generated by Xtext
 */
package org.xtext.grl.tgrl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TGRLRuntimeModule extends org.xtext.grl.tgrl.AbstractTGRLRuntimeModule {

}
