/**
 * generated by Xtext
 */
package org.xtext.grl.tgrl.validation;

import org.xtext.grl.tgrl.validation.AbstractTGRLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class TGRLValidator extends AbstractTGRLValidator {
}
